### ISSUE TITLE
Add build, watch script to the Project

### ISSUE THREAD

**Issue by namangupta01** [publiclab/simple-data-grapher#8]
With the introducing of new project structure, we want to use the various dependencies present in the project package.json file. For that we will use `require` but for using it we need something that bundles up all the required libraries or modules. For that, we should have any kind of task runner for compiling node_modules. What do you say @jywarren and @IshaGupta18 ? Should we go for grunt or something else?

**Comment by IshaGupta18** [comment]
You are right about this, however, I honestly don't have much experience with the dependency stuff, so I'll have to look up grunt before I can comment on this. Thanks!

**Comment by namangupta01** [comment]
No problem! Even I don't have much experience in it :p
But you will become comfortable in some time.

**Comment by jywarren** [comment]
I think @rexagod was suggesting that this may be a good time to look at
Gulp instead. Perhaps we could hear from @rexagod and think about the
pros/cons a bit more?

**Comment by namangupta01** [comment]
`grunt-browserify` do not let the variables available in the browser console for debugging. In case you know, please let me know @jywarren .

**Comment by rexagod** [comment]
Why I usually recommend gulp is because of a) it uses [transform node streams](https://nodejs.org/api/stream.html#stream_class_stream_transform) rather than temp files, thus giving a nice boost to build tasks and b) it has a cleaner API. That being said, point (a) only should be taken into consideration if the modules are really big, else there's negligible difference between the two, so I believe if one is more inclined towards using grunt over gulp, we could work with that, although, as stated above, and to be on the safer side, I personally would recommend using gulp. That being said, the tasks that I've include in my "soc modules", are as follows.

- Babel, because we DEFINITELY want a transpiler to create all those backward compatible poly-fills
- Mocha, with Istanbul coverage
- ESLint, using Airbnb's config to maintain code quality
- Minifier

A more radical approach (and what I'm doing with my modules) could however be NOT to use grunt or gulp at all, and rather assigning the tasks to npm run and test commands, while including independent packages, hence not being dependent on gulp or grunt communities to upgrade support or fix bugs, and rather working with the original source codes. I did this especially because of some similar instances in the past where "grunt-customized" versions of different task packages seemed to get late updates, bugfixes, and in general we not much maintained at all. This would prevent that. ALSO, this would mean we would have to deal with different task runners across different repos and all the problem that could stem from that.

For eg.,
https://github.com/publiclab/PublicLab.Editor/pull/168
https://github.com/publiclab/inline-markdown-editor/pull/29
that tended to root due to a callback param not being passed
https://github.com/gruntjs/grunt-contrib-jasmine/pull/267

@namangupta01 @IshaGupta18 I can share a boilerplate with the above packages and configs if you decide to adopt this ("npm") approach.

@jywarren I would like to know your thoughts on using a task runner at all, instead doing so using npm, and if you agree or not, so I can make the appropriate changes and include (or not) a task runner as per you opinion.

PS. I found something that concurs with my thoughts above [here](https://medium.freecodecamp.org/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8), this should clarify things further.

**Comment by rexagod** [comment]
Why I usually recommend gulp is because of a) it uses [transform node streams](https://nodejs.org/api/stream.html#stream_class_stream_transform) rather than temp files, thus giving a nice boost to build tasks and b) it has a cleaner API. That being said, point (a) only should be taken into consideration if the modules are really big, else there's negligible difference between the two, so I believe if one is more inclined towards using grunt over gulp, we could work with that, although, as stated above, and to be on the safer side, I personally would recommend using gulp. That being said, the tasks that I've included in my "soc modules (ORB, AS, etc.)", are as follows.

- Babel, because we DEFINITELY want a transpiler to create all those backward compatible poly-fills
- Mocha, with Istanbul coverage
- ESLint, using Airbnb's config to maintain code quality
- Minifier

A more radical approach (and what I'm doing with my modules) could however be NOT to use grunt or gulp at all, and rather assigning the tasks to npm run and test commands, while including independent packages, hence not being dependent on gulp or grunt communities to upgrade support or fix bugs, and rather working with the original source codes. I did this especially because of some similar instances in the past where "grunt-customized" versions of different task packages seemed to get late updates, bugfixes, and in general we not much maintained at all. This would prevent that. ALSO, this would mean we wouldn't have to deal with different task runners across different repos and all the problems that could stem from that.

For eg.,
https://github.com/publiclab/PublicLab.Editor/pull/168
https://github.com/publiclab/inline-markdown-editor/pull/29
that tended to misbehave due to a callback param not being passed
https://github.com/gruntjs/grunt-contrib-jasmine/pull/267

@namangupta01 @IshaGupta18 I can share a boilerplate with the above packages and configs if you decide to adopt this ("npm") approach.

@jywarren I would like to know your thoughts on not using a task runner at all, instead doing so using npm, and if you agree or not, so I can make the appropriate changes and include (or not) a task runner as per your opinion.

PS. I found something that concurs with my thoughts above [here](https://medium.freecodecamp.org/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8), and this should clarify things further.

**Comment by namangupta01** [comment]
@rexagod I think you are right. We should do the runner task using `npm`.

**Comment by namangupta01** [comment]
Done in the pr #10. You can have a look.
